name: 'Docker publish'
inputs:
  token:
    description: 'auth token'
    required: true
    default: ''
  ghost-api-key:
    description: 'ghost key'
    required: true
    default: ''
  ghost-url:
    description: 'ghost url'
    required: true
    default: ''
  logo-url:
    description: 'logo'
    required: true
    default: ''
  rss-feed:
    description: 'rss feed'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        secrets: |
          "GHOST_API_KEY=${{ inputs.ghost-api-key }}"
          "GHOST_URL=${{ inputs.ghost-url }}"
          "LOGO_URL=${{ inputs.logo-url }}"
          "RSS_FEED=${{ inputs.rss-feed }}"
