name: Publish

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ghost-api-key: ${{ secrets.GHOST_API_KEY }}
          ghost-url: ${{ vars.GHOST_URL }}
          logo-url: ${{ vars.LOGO_URL }}
          rss-feed: ${{ vars.RSS_FEED }}