name: Publish

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: cd site-writer
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
