# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [ "master" ]
    paths:
      - 'site-writer/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GHOST_API_KEY: ${{ secrets.GHOST_API_KEY }}
  GHOST_URL: ${{ vars.GHOST_URL }}
  LOGO_URL: ${{ vars.LOGO_URL }}
  RSS_FEED: ${{ vars.RSS_FEED }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Release-Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: ghost-writer
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - run: cd site-writer
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/ci-setup
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/docker-publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
